### ISSUE TITLE
ReadTheDocs’ "Edit on GitHub" link isn’t working

### ISSUE THREAD

**Issue by thibaudcolas** [mwesterhof/wagtail_formation#1]
From the documentation homepage, this link takes me to: https://github.com/mwesterhof/wagtail_formation/edit/master/docs/index.md

It looks like the branch name is wrong, and possibly the folder structure needs one more `docs` folder?

**Comment by mwesterhof** [comment]
@thibaudcolas Thanks for reporting that issue, I fixed it. Turns out that mkdocs has some interesting quirks I didn't account for 😄

**Comment by mwesterhof** [comment]
fixed in latest update
